version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:latest
    working_directory: ~/blog
    steps:
      - checkout
      - run:
          name: Setup git
          command: git config --global user.email "dev@scon.io" && git config --global user.name "Sangwon Kim"
      - run:
          name: Install dependencies
          command: npm install hexo
      - run:
          name: Generate
          command: npx hexo generate
      - run:
          name: Deploy
          command: npx hexo deploy