
# html lang
language: en

# main menu navigation
menu:
  # Home:
  #   url: /
  # About:
  #   url: /about
  # Archives:
  #   url: /archives
  # Projects:
  #   url: /projects

# stylesheets loaded in the <head>
stylesheets:
- /css/bootstrap.min.css
- /css/reset.css
- /css/main.css

# scripts loaded in the end of the body
scripts:
- /js/bootstrap.min.js
- /js/zen.js
